CREATE TABLE IF NOT EXISTS images (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    prompt TEXT NOT NULL,
    numbers INTEGER NOT NULL,
    textSize VARCHAR(255) NOT NULL
);
